---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: common-bionic
    source:
      type: image
      alias: ubuntu/bionic/amd64
    architecture: x86_64
    profiles:
       - default
#       - nested
#      - gui
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: lxd
verifier:
  name: testinfra
  lint:
    name: flake8
