# Install with: `ansible-galaxy install -r requirements.yml`

# from GitHub, overriding the name and specifying a specific tag
- src: https://github.com/geerlingguy/ansible-role-clamav.git
  version: 1.3.1
  name: geerlingguy.clamav
