# Manually install with: `ansible-galaxy install -r requirements.yml`

- src: https://github.com/geerlingguy/ansible-role-git.git
  name: geerlingguy.git

- src: https://github.com/geerlingguy/ansible-role-pip.git
  name: geerlingguy.pip

- src: https://github.com/geerlingguy/ansible-role-clamav.git
  name: geerlingguy.clamav
  
- src: https://github.com/geerlingguy/ansible-role-docker.git
  name: geerlingguy.docker

# required for docker testing
- src: https://github.com/weareinteractive/ansible-users
  version: 1.11.1
  name: weareinteractive.users

- src: https://github.com/jdauphant/ansible-role-vagrant.git
  version: v1.1
  name: jdauphant.vagrant

#- src: https://github.com/Oefenweb/ansible-nodejs.git
#  version: v5.0.0
#  name: oefenweb.nodejs

